// Run with: node seed.js   (after setting up .env)
require("dotenv").config();
const mongoose = require("mongoose");
const connectDB = require("./config/db");
const Product = require("./Models/Product");

const products = [
  {
    name: "EcoMax 450W Solar Panel",
    slug: "ecomax-450w-solar-panel",
    description: "High-efficiency monocrystalline panel with 22% efficiency.",
    category: "Solar Panels",
    brand: "EcoMax",
    image: "/images/product-panel.jpg",
    price: 185000,
    originalPrice: 219000,
    countInStock: 50,
    rating: 4.8,
    numReviews: 124,
    featured: true,
  },
  {
    name: "Helios X9 Mono Panel 400W",
    slug: "helios-x9-mono-panel-400w",
    description: "Premium monocrystalline panel with anti-reflective coating for low-light performance.",
    category: "Solar Panels",
    brand: "Helios",
    image: "/images/product-panel.jpg",
    price: 162000,
    originalPrice: 190000,
    countInStock: 65,
    rating: 4.7,
    numReviews: 98,
    featured: false,
  },
  {
    name: "SolarFlex Flexible Panel 120W",
    slug: "solarflex-flexible-panel-120w",
    description: "Lightweight, bendable panel for boats, RVs, and curved roofs.",
    category: "Solar Panels",
    brand: "SolarFlex",
    image: "/images/product-panel.jpg",
    price: 78000,
    originalPrice: 95000,
    countInStock: 40,
    rating: 4.4,
    numReviews: 41,
    featured: false,
  },
  {
    name: "PowerVault 10kWh Battery",
    slug: "powervault-10kwh-battery",
    description: "Lithium-ion home battery for whole-home backup.",
    category: "Batteries",
    brand: "PowerVault",
    image: "/images/product-battery.jpg",
    price: 3800000,
    originalPrice: 4300000,
    countInStock: 12,
    rating: 4.9,
    numReviews: 87,
    featured: true,
  },
  {
    name: "VoltCell LiFePO4 5kWh Battery",
    slug: "voltcell-lifepo4-5kwh-battery",
    description: "Compact lithium iron phosphate battery with 6,000+ cycle lifespan.",
    category: "Batteries",
    brand: "VoltCell",
    image: "/images/product-battery.jpg",
    price: 2100000,
    originalPrice: 2450000,
    countInStock: 18,
    rating: 4.8,
    numReviews: 63,
    featured: false,
  },
  {
    name: "TitanPower 15kWh Battery Bank",
    slug: "titanpower-15kwh-battery-bank",
    description: "Stackable battery bank for large homes and small commercial sites.",
    category: "Batteries",
    brand: "TitanPower",
    image: "/images/product-battery.jpg",
    price: 5200000,
    originalPrice: 5900000,
    countInStock: 8,
    rating: 4.9,
    numReviews: 34,
    featured: true,
  },
  {
    name: "InverGen 5kW Hybrid Inverter",
    slug: "invergen-5kw-hybrid-inverter",
    description: "Hybrid inverter with grid-tie and battery backup support.",
    category: "Inverters",
    brand: "InverGen",
    image: "/images/product-inverter.jpg",
    price: 950000,
    originalPrice: 1100000,
    countInStock: 20,
    rating: 4.7,
    numReviews: 56,
    featured: true,
  },
  {
    name: "FluxCore 10kW Hybrid Inverter",
    slug: "fluxcore-10kw-hybrid-inverter",
    description: "High-capacity inverter for larger homes with dual MPPT charge controllers.",
    category: "Inverters",
    brand: "FluxCore",
    image: "/images/product-inverter.jpg",
    price: 1750000,
    originalPrice: 2000000,
    countInStock: 15,
    rating: 4.7,
    numReviews: 42,
    featured: false,
  },
  {
    name: "GridTie 3kW Pure Sine Inverter",
    slug: "gridtie-3kw-pure-sine-inverter",
    description: "Compact pure sine wave inverter ideal for small apartments and shops.",
    category: "Inverters",
    brand: "GridTie",
    image: "/images/product-inverter.jpg",
    price: 480000,
    originalPrice: 560000,
    countInStock: 30,
    rating: 4.5,
    numReviews: 71,
    featured: false,
  },
  {
    name: "SunCharge Portable 200W",
    slug: "suncharge-portable-200w",
    description: "Foldable solar charger for camping and emergencies.",
    category: "Chargers",
    brand: "SunCharge",
    image: "/images/product-charger.jpg",
    price: 145000,
    originalPrice: 179000,
    countInStock: 80,
    rating: 4.6,
    numReviews: 210,
    featured: true,
  },
  {
    name: "VoltLink EV Charger 22kW",
    slug: "voltlink-ev-charger-22kw",
    description: "Fast home EV charger with app-based scheduling and load balancing.",
    category: "Chargers",
    brand: "VoltLink",
    image: "/images/product-charger.jpg",
    price: 650000,
    originalPrice: 780000,
    countInStock: 22,
    rating: 4.8,
    numReviews: 98,
    featured: false,
  },
  {
    name: "MountKit Universal Roof Mounting Set",
    slug: "mountkit-universal-roof-mounting-set",
    description: "Corrosion-resistant aluminum rail kit for pitched and flat roof panel installs.",
    category: "Accessories",
    brand: "MountKit",
    image: "/images/product-panel.jpg",
    price: 62000,
    originalPrice: 75000,
    countInStock: 55,
    rating: 4.5,
    numReviews: 29,
    featured: false,
  },
];

(async () => {
  try {
    await connectDB();
    await Product.deleteMany();
    await Product.insertMany(products);
    console.log("✅ Seeded products");
    process.exit(0);
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
})();
